(define (navigate-context xs exp)
  (if (null? xs)
      exp
      (if (existsi exp (car xs))
          (navigate-context (cdr xs) (geti exp (car xs)))
          ':none)))

(define (orfun . args)
  (if (null? args)
      #f
      (if (car args)
          #t
          (apply orfun (cdr args)))))

;; meta-circular evaluator
(define (meta-ev-exp more-cases)
  `(begin
    (set! _ctx (get this '(:ctx) '()))
    (set! _e (navigate-context (reverse _ctx) (get this '(:exp))))
    (set! _ps (get this '(:pendings) '(())))
    (set! _pending (car _ps))
    (if (eq? _e ':none)
        (begin
          (set! _ctx (cdr _ctx))
          (set! _ps (cdr _ps))
          (set! _e (navigate-context (reverse _ctx) (get this '(:exp)))))
        (if (not (eq? _result ':none))
            (if (not (null? (cdr _ps)))
                (begin
                  (set! _ps (cons (cons (caar _ps) (cadr _ps)) (cddr _ps))))
                (if (not (null? (car _ps)))
                    (begin
                      (set! _ps (cons (cons (caar _ps) '()) '())))))))
    (set! _pending (car _ps))
    (set!
     _next-ctx
     (if (null? _ctx)
         '()
         (cons (+ 1 (car _ctx)) (cdr _ctx))))
    (set! _result ':none)
    (set! _pop? #f)
    (display _e) (newline)
    (display _ps) (newline)
    (if (symbol? _e)
        (begin
          (set! _result (get this (list ':env _e)))
          (set! _ctx _next-ctx))
        (if (orfun (number? _e) (boolean? _e) (string? _e))
            (begin
              (set! _result _e)
              (set! _ctx _next-ctx))
            (if (orfun
                 (tagged? '+ _e)
                 (tagged? '- _e)
                 (tagged? '* _e)
                 (tagged? '= _e)
                 (tagged? '< _e)
                 (tagged? '<= _e)
                 (tagged? 'not _e)
                 (tagged? 'cons _e)
                 (tagged? 'car _e)
                 (tagged? 'cdr _e)
                 (tagged? 'dict _e)
                 (tagged? 'copy _e)
                 (tagged? 'display _e)
                 (tagged? 'newline _e)
                 (tagged? 'list _e)
                 (tagged? 'null? _e)
                 (tagged? 'length _e)
                 (tagged? 'reverse _e)
                 (tagged? 'symbol? _e)
                 (tagged? 'number? _e)
                 (tagged? 'boolean? _e)
                 (tagged? 'string? _e)
                 (tagged? 'eq? _e)
                 (tagged? 'tagged? _e)
                 (tagged? 'apply _e)
                 (tagged? 'eval _e)
                 (tagged? 'error _e)
                 (tagged? 'existsi _e)
                 (tagged? 'geti _e)
                 (tagged? 'orfun _e)
                 (tagged? 'navigate-context _e)
                 (tagged? 'format _e))
                (if (= (length _pending) (length (cdr _e)))
                    (begin
                      (set! _result
                            (apply
                             (eval (car _e))
                             (reverse _pending)))
                      (set! _pop? #t)
                      (set! _ctx _next-ctx))
                    (set! _ctx (cons 1 _ctx)))
                (if (tagged? 'set! _e)
                    (if (= (length _pending) 1)
                        (begin
                          (set! _x (geti _e 1))
                          (set! _v (geti _pending 0))
                          (upd! this (list ':env _x) _v)
                          (set! _result _v)
                          (set! _pop? #t)
                          (set! _ctx _next-ctx))
                        (set! _ctx (cons 2 _ctx)))
                    (if (tagged? 'get _e)
                        (if (= (length _pending) (length (cdr _e)))
                            (begin
                              (set! _pending_rev (cons 'get (reverse _pending)))
                              (set! _dict (geti _pending_rev 1))
                              (set! _selector (geti _pending_rev 2))
                              (if (existsi _e 3)
                                  (set! _result (get _dict _selector (geti _pending_rev 3)))
                                  (set! _result (get _dict _selector)))
                              (set! _pop? #t)
                              (set! _ctx _next-ctx))
                            (set! _ctx (cons 1 _ctx)))
                        (if (tagged? 'upd! _e)
                            (if (= (length _pending) (length (cdr _e)))
                                (begin
                                  (set! _pending_rev (cons 'upd! (reverse _pending)))
                                  (set! _dict (geti _pending_rev 1))
                                  (set! _selector (geti _pending_rev 2))
                                  (set! _val (geti _pending_rev 3))
                                  (upd! _dict _selector _val)
                                  (set! _pop? #t)
                                  (set! _ctx _next-ctx))
                                (set! _ctx (cons 1 _ctx)))
                            (if (tagged? 'quote _e)
                                (begin
                                  (set! _result (geti _e 1))
                                  (set! _ctx _next-ctx))
                                (if (tagged? 'if _e)
                                    (if (= (length _pending) 1)
                                        (if (geti _pending 0)
                                            (set! _ctx (cons 2 _ctx))
                                            (set! _ctx (cons 3 _ctx)))
                                        (if (= (length _pending) 2)
                                            (begin
                                              (set! _result (geti _pending 0))
                                              (set! _pop? #t)
                                              (set! _ctx _next-ctx))
                                            (set! _ctx (cons 1 _ctx))))
                                    (if (tagged? 'begin _e)
                                        (if (= (length _pending) (length (cdr _e)))
                                            (begin
                                              (display _e) (newline)
                                              (display _pending) (newline)
                                              (set! _result (car _pending))
                                              (set! _pop? #t)
                                              (set! _ctx _next-ctx))
                                            (set! _ctx (cons 1 _ctx)))
                                        (if (tagged? 'this _e)
                                            (begin
                                              (set! _result this)
                                              (set! _ctx _next-ctx))
                                            ,(more-cases '(error 'evl (format "unknown expression ~a" _e)))))))))))))
    (upd! this '(:ctx) _ctx)
    (if (not (eq? _result ':none))
        (upd! this '(:pendings) (cons (list _result) _ps)))))

(define meta-ev
  (eval `(lambda (this) ,(meta-ev-exp (lambda (x) x)))))
