(define (tracer process)
  `((:eval . ,(lambda (this exp env)
                (let ((penv (get process ':env)))
                  (format #t "~a\n" penv)
                  (upd! env ':trace (lambda (ts) (cons (full-copy penv) ts)))
                  (if (get (get process ':env) ':done #f)
                      (begin
                        (upd! env ':trace (lambda (ts) (reverse ts)))
                        (upd! env ':done (lambda (old) #t)))
                      (run process)))
                env))
    (:exp . ':none)
    (:env . ((:done . #f) (:trace . ())))))
